# Generated by Django 3.2.25 on 2025-08-29 17:13

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='day_fixed_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed charge for daytime (6:00–18:00)', max_digits=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='id_proofs/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='night_end',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
        migrations.AddField(
            model_name='driver',
            name='night_fixed_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed charge for night (18:00–6:00)', max_digits=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='night_start',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='driver',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='driver_profile/'),
        ),
    ]
