# Generated by Django 3.2.25 on 2025-08-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='estimated_distance_km',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='estimated_duration_min',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='surge_multiplier',
        ),
        migrations.AlterField(
            model_name='ride',
            name='purpose_notes',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
