# Generated by Django 3.2.25 on 2025-08-30 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_auto_20250830_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='purpose_notes',
        ),
    ]
