# Generated by Django 5.2.5 on 2025-09-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_riderequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('auto_cancelled', 'Auto Cancelled')], default='pending', max_length=20),
        ),
    ]
