# Generated by Django 3.2.25 on 2025-08-29 17:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='base_fare_per_hour',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='base_fare_per_km',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='listed',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='per_km_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fare per km when vehicle hired with driver', max_digits=6),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='per_min_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fare per minute (optional)', max_digits=6),
        ),
    ]
